UPDATE BIG_SCREEN_H SET EFFICIENCY_PERC = 98 WHERE CD_LINEA = '007';
UPDATE BIG_SCREEN_H SET CHECKED_QTY = 760 WHERE CD_LINEA = '007';
UPDATE BIG_SCREEN_H SET AVG_TRACKING = 45 WHERE CD_LINEA = '007';
UPDATE BIG_SCREEN_H SET ACTIVE_CADRE = 29 WHERE CD_LINEA = '007';
UPDATE BIG_SCREEN_H SET TOTAL_MACHINES = 28 WHERE CD_LINEA = '007';